name: Deploy to Firebase Hosting

on:
  push:
    branches:
      - main # Change to master if your branch name in GitHub Desktop is master

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      # Runs your trusted original container tool using your pre-saved secret key string
      - name: Deploy to Firebase Hosting
        uses: w9jds/firebase-action@master
        with:
          args: deploy --only hosting
        env:
          FIREBASE_TOKEN: ${{ secrets.FIREBASE_TOKEN }}
          PROJECT_PATH: "."
